apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: yash5090/youtube:latest
          ports:
            - containerPort: 3000  # Your NodeJS App will listen on this Port
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # Port for HTTP traffic
      targetPort: 3000  # Your NodeJS App will execute on this Port
  type: NodePort
